In [1]:
import cv2
import numpy as np
from os import listdir
from os.path import isfile,join

C:\Users\gupta\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\gupta\anaconda3\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
C:\Users\gupta\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\gupta\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:\n%s" %


In [2]:
path= './Image_Sudeep_Dataset/'

#We use listdir to get all fles and directories of the path.
#We use isfile to take only files and not directories.
photos= [f for f in listdir(path) if isfile(join(path,f))]

In [3]:
type(photos)      #list
type(photos[0])   #string

str

In [4]:
#Now create empty arrays to store the photos and labels.
Training_data,Labels = [],[]

for i,files in enumerate(photos):
    photo_path= path + files
    photo = cv2.imread(photo_path,cv2.IMREAD_GRAYSCALE)
    
    Training_data.append(np.asarray(photo))
    Labels.append(i)
    
#Convert Labels to numpyarray
Labels= np.asarray(Labels,dtype= np.int32)

In [5]:
type(photo)

numpy.ndarray

In [6]:
Labels

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
type(Labels)

numpy.ndarray

In [8]:
type(Training_data)

list

In [9]:
Training_data

[array([[168, 128, 101, ..., 220, 223, 225],
        [ 93,  61,  75, ..., 230, 226, 224],
        [ 74,  51,  76, ..., 224, 220, 219],
        ...,
        [148, 142, 138, ..., 221, 221, 222],
        [144, 139, 138, ..., 222, 222, 223],
        [142, 139, 140, ..., 219, 219, 220]], dtype=uint8),
 array([[ 50,  46,  48, ..., 198, 193, 193],
        [ 52,  57,  63, ..., 196, 195, 195],
        [ 58,  66,  71, ..., 194, 198, 196],
        ...,
        [112, 112, 113, ..., 188, 192, 190],
        [119, 116, 115, ..., 191, 192, 189],
        [121, 118, 117, ..., 192, 193, 189]], dtype=uint8),
 array([[ 22,  19,  15, ...,  33,  39,  51],
        [ 21,  18,  14, ...,  31,  37,  50],
        [ 18,  16,  12, ...,  31,  36,  48],
        ...,
        [144, 142, 143, ..., 208, 210, 211],
        [164, 163, 165, ..., 208, 211, 212],
        [168, 167, 167, ..., 208, 211, 211]], dtype=uint8),
 array([[138,  77,  56, ..., 192, 194, 194],
        [105,  34,  50, ..., 190, 192, 194],
        [ 73,  4

In [10]:
Training_data = np.asarray(Training_data)

In [11]:
#Now train the model using LBPH function

sudeep_model= cv2.face_LBPHFaceRecognizer.create()

sudeep_model.train(Training_data,Labels)
print('Model trained successfully')

Model trained successfully


In [12]:
#NOW OUR AUTO EMAIL FUNCTION
import smtplib
def Auto():
    server = smtplib.SMTP_SSL("smtp.gmail.com",465)
    server.login("ggsg126@gmail.com","sudeepfake@126")

    sender_mail="ggsg162@gmail.com"
    #reciever_mail="bshivam200@gmail.com"
    reciever_mail="guptaasudeeep152@gmail.com"
    message= '''
    Hey,
        Your face has been detected-Sudeep.
        Access Granted..'''

    server.sendmail(sender_mail,reciever_mail,message)
    server.quit()



In [13]:
import cv2
import numpy as np
import os

face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_detector(img, size=0.5):
    
    # Convert image to grayscale
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray, 1.3, 5)
    if faces is ():
        return img, []
    
    
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        roi = img[y:y+h, x:x+w]
        roi = cv2.resize(roi, (200, 200))
    return img, roi


# Open Webcam
cap = cv2.VideoCapture(0)

while True:

    ret, frame = cap.read()
    
    image, face = face_detector(frame)
    
    try:
        face = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)

        # Pass face to prediction model
        # "results" comprises of a tuple containing the label and the confidence value
        results = sudeep_model.predict(face)
        # harry_model.predict(face)
        
        if results[1] < 500:
            confidence = int( 100 * (1 - (results[1])/400) )
            display_string = str(confidence) + '% Confident it is User'
            
        cv2.putText(image, display_string, (100, 120), cv2.FONT_HERSHEY_COMPLEX, 1, (255,120,150), 2)
        
        if confidence > 89:
            cv2.putText(image, "Hi Sudeep", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            cv2.imshow('Face Recognition', image )
            #os.system("chrome https://www.youtube.com/")
            # os.system("date")
            Auto()
            print("Now auto mail will be generated:")
            
            break
         
        else:
            
            cv2.putText(image, "I dont know, who are you?", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
            cv2.imshow('Face Recognition', image )

    except:
        cv2.putText(image, "No Face Found!", (220, 120) , cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
        cv2.putText(image, "looking for face....", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
        cv2.imshow('Face Recognition', image )
        pass
        
    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break
        
cap.release()
cv2.destroyAllWindows()     

<>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-13-3206566767ab>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


Now auto mail will be generated:
